---
collections:
  - name: devsec.hardening
roles:
  - name: geerlingguy.git
  - name: manala.vim
  - name: geerlingguy.security
  - name: geerlingguy.docker
  - name: linux-system-roles.cockpit
  - name: geerlingguy.pip
  - name: geerlingguy.nginx
  - name: weareinteractive.ufw
  - name: jenstimmerman.vaultwarden
  - name: naftulikay.rust-dev
  - name: geerlingguy.java
  - name: gantsign.golang
  - name: geerlingguy.ruby
  - name: geerlingguy.nodejs
  - name: gantsign.maven
  - name: secfigo.terraform
  - name: geerlingguy.ansible
  - name: do1jlr.gitea
