---
- name: Gather facts
  setup:

- name: Download dotfiles
  git:
    repo: "https://github.com/GonzaloAlvarez/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"

- name: Download gear repo
  git:
    repo: 'https://github.com/GonzaloAlvarez/gear.git'
    dest: '{{ ansible_env.HOME }}/.gear'

- name: Install dotfiles
  shell: "{{ ansible_env.HOME }}/.dotfiles/build.sh {{ inventory_hostname }}"
  when: ansible_facts['os_family'] != "Darwin"

- name: Download vim dotfiles
  git:
    repo: "https://github.com/GonzaloAlvarez/vim.git"
    dest: "{{ ansible_env.HOME }}/.vim"
