---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: dev-cpp-mol-test
    box: debian/buster64
provisioner:
  name: ansible
verifier:
  name: ansible
