---
- name: Run whoami without become.
  local_action: "command whoami"
  changed_when: false
  become: false
  register: whoami

- name: Set a fact with the user name.
  set_fact:
    login_user: "{{ whoami.stdout }}"

- name: Retrieve SSH Config facts
  local_action: "ssh_config_facts host=passwords user={{ login_user }}"
  register: ssh_config_facts
  become: False

- name: Set main_private_keyfile
  set_fact:
    main_private_key_file: "{{ ssh_config_facts.host_identity_file }}"

- name: Check if {{ main_user }} exists in the system
  local_action: "command ssh -q -o BatchMode=yes -o ConnectTimeout=3 -l {{ main_user }} -i {{ main_private_key_file }} {{ inventory_hostname }} 'echo ok'"
  register: test_user
  become: False
  ignore_errors: true
  changed_when: false

- name: Setup and gather facts for this host
  action: setup
  when: test_user is failed

- name: Start user management tasks
  block:
    - import_tasks: groups.yml
    - import_tasks: users.yml
    - import_tasks: sudoers.yml
    - import_tasks: keys.yml
    - import_tasks: purge-users.yml
  when: test_user is failed
  become: True

