---
- name: Verify role
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Get restic bin
      stat:
        path: '{{ restic_install_path }}/restic'
      register: restic_stat

    - name: Validate restic bin
      assert:
        that: restic_stat.stat.exists and restic_stat.stat.size != 0
