---
nginx_worker_processes: "auto"
nginx_remove_default_vhost: true

nginx_upstreams:
  - name: proxmox
    strategy: "ip_hash"
    keepalive: 60
    servers: { "localhost:8006" }

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "{{ ansible_host }}"
    return: "301 https://{{ ansible_host }}$request_uri"
    filename: "{{ ansible_host }}.80.conf"

  - listen: "443 ssl http2"
    server_name: "{{ ansible_host }}"
    filename: "{{ ansible_host }}.conf"
    extra_parameters: |
      ssl_certificate "/etc/ssl/certs/ssl-cert-{{ ansible_host }}.crt";
      ssl_certificate_key "/etc/ssl/private/ssl-cert-{{ ansible_host }}.key";
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!aNULL:!MD5;
      proxy_redirect off;
      location / {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_pass https://localhost:8006;
          proxy_buffering off;
          client_max_body_size 0;
          proxy_connect_timeout  3600s;
          proxy_read_timeout  3600s;
          proxy_send_timeout  3600s;
          send_timeout  3600s;
      }
      location /status/ {
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_pass https://localhost:9090;
          proxy_buffering off;
          gzip off;
          client_max_body_size 0;
          proxy_connect_timeout  3600s;
          proxy_read_timeout  3600s;
          proxy_send_timeout  3600s;
          send_timeout  3600s;
      }
