---
- name: Set 'HandlePowerKey=poweroff' in /etc/systemd/logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandlePowerKey='
    line: 'HandlePowerKey=poweroff'

- name: Set 'HandleLidSwitch=ignore' in /etc/systemd/logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandleLidSwitch='
    line: 'HandleLidSwitch=ignore'

- name: Set 'IdleAction=ignore' in /etc/systemd/logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'IdleAction='
    line: 'IdleAction=ignore'

- name: Set 'IdleActionSec=30min' in /etc/systemd/logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'IdleActionSec='
    line: 'IdleActionSec=30min'

- name: disable services to prevent laptop standby 
  systemd:
    name: "{{ item }}"
    state: stopped
    masked: yes
    enabled: no
  with_items:
    - "sleep.target"
    - "suspend.target" 
    - "hibernate.target"
    - "hybrid-sleep.target"

- name: force systemd reload 
  systemd: daemon_reload=yes

- name: Add shutdown if unplugged rule
  copy:
    content: 'SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_ONLINE}=="0", RUN+="/usr/sbin/halt -p"'
    dest: '/etc/udev/rules.d/50-ac-unplugged.rules'
    mode: 0644
