galaxy_info:
  author: Gonzalo Alvarez
  description: My personal private keys

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  
