---
- name: install debian-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev

- name: install debian-required pip packages
  pip:
    name:
      - appdirs
      - packaging
      - aiohttp_cors
    state: present
    executable: pip3.9

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
