---
galaxy_info:
  role_name: restic_run
  namespace: restic_run
  author: 'Gonzalo Alvarez'
  description: Restic Backup Run Role
  company: 'Gonzalo Alvarez'
  license: 'Apache 2.0'
  min_ansible_version: '2.7'

  platforms:
    - name: Debian
      versions:
        - 1-

  galaxy_tags:
    - system

dependencies:
  - role: 'restic'
    become: true
